# Save cookies as JMeter variables so we can inspect them mid-flow
CookieManager.save.cookies=true
# Log received cookies and any cookies rejected by the policy
CookieManager.check.cookies=false
# Default cookie policy used when CookieManager.implementation==HC4CookieHandler
CookieManager.policy=standard
# Cookie handler implementation
CookieManager.implementation=org.apache.jmeter.protocol.http.control.HC4CookieHandler

# Enable verbose cookie logging
log_level.org.apache.http.client.protocol=DEBUG
log_level.org.apache.http.headers=DEBUG
log_level.org.apache.jmeter.protocol.http.control=DEBUG
